# fly.toml app configuration file generated for publy-fullstack-example on 2025-02-09T18:41:01+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'publy-fullstack-example'
primary_region = 'arn'

[build]
  image = 'ghcr.io/nilshartmann/ecolify-backend-native:latest'

[http_service]
  internal_port = 20080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
